cargo clean 
cargo build --release --features 'metrics,nwr'

echo 'pihole'
RUST_BACKTRACE=1 /usr/bin/time -v -a -o ./tests/results/memory/pihole_nwr ./target/release/reef --baselines --doc "ad.stackoverflow.com/uid?=abd?utm_source=partnerize&utm_medium=affiliate&utm_campaign=88849&utm_content=2-500037&clickId=1234567" --metrics ./tests/results/timings/pihole --batch-size 8 --re "^ad([sxv]?[0-9]*|system)[_.-]([^.[:space:]]+\.){1,}|[_.-]ad([sxv]?[0-9]*|system)[_.-]" ascii;
RUST_BACKTRACE=1 /usr/bin/time -v -a -o ./tests/results/memory/pihole_nwr ./target/release/reef --baselines --doc "adimage101.adserver99.telemetry.com/uid?=abd?utm_source=partnerize&utm_medium=affiliate&utm_campaign=88849&utm_content=2-1234323" --metrics ./tests/results/timings/pihole --batch-size 8 --re "^(.+[_.-])?adse?rv(er?|ice)?s?[0-9]*[_.-]" ascii;
RUST_BACKTRACE=1 /usr/bin/time -v -a -o ./tests/results/memory/pihole_nwr ./target/release/reef --baselines --doc "adimage101.testingads.telemetry.com/uid?=abd?utm_source=partnerize&utm_medium=affiliate&utm_campaign=88849&utm_content=2-5000379" --metrics ./tests/results/timings/pihole --batch-size 8 --re "^(.+[_.-])?telemetry[_.-]" ascii;
RUST_BACKTRACE=1 /usr/bin/time -v -a -o ./tests/results/memory/pihole_nwr ./target/release/reef --baselines --doc "adimage101.testingads.com/uid?=abd?utm_source=partnerize&utm_medium=affiliate&utm_campaign=88849&utm_content=2-500037&clickId=12" --metrics ./tests/results/timings/pihole --batch-size 8 --re "^adim(age|g)s?[0-9]*[_.-]" ascii;
RUST_BACKTRACE=1 /usr/bin/time -v -a -o ./tests/results/memory/pihole_nwr ./target/release/reef --baselines --doc "adtracker101.testingads.com/uid?=abd?utm_source=partnerize&utm_medium=affiliate&utm_campaign=88849&utm_content=2-500037&clickId=" --metrics ./tests/results/timings/pihole --batch-size 8 --re "^adtrack(er|ing)?[0-9]*[_.-]" ascii;
RUST_BACKTRACE=1 /usr/bin/time -v -a -o ./tests/results/memory/pihole_nwr ./target/release/reef --baselines --doc "advertising101.testingads.com/uid?=abd?utm_source=partnerize&utm_medium=affiliate&utm_campaign=88849&utm_content=2-500037&click1" --metrics ./tests/results/timings/pihole --batch-size 8 --re "^advert(s|is(ing|ements?))?[0-9]*[_.-]" ascii;
RUST_BACKTRACE=1 /usr/bin/time -v -a -o ./tests/results/memory/pihole_nwr ./target/release/reef --baselines --doc "affiliate.link.testingads.com/uid?=abd?utm_source=partnerize&utm_medium=affiliate&utm_campaign=88849&utm_content=2-500037&clickI" --metrics ./tests/results/timings/pihole --batch-size 8 --re "^aff(iliat(es?|ion))?[_.-]" ascii;
RUST_BACKTRACE=1 /usr/bin/time -v -a -o ./tests/results/memory/pihole_nwr ./target/release/reef --baselines --doc "analytics.testingads.com/uid?=abd?utm_source=partnerize&utm_medium=affiliate&utm_campaign=88849&utm_content=2-500037&clickId=123" --metrics ./tests/results/timings/pihole --batch-size 8 --re "^analytics?[_.-]" ascii;
RUST_BACKTRACE=1 /usr/bin/time -v -a -o ./tests/results/memory/pihole_nwr ./target/release/reef --baselines --doc "banners.testingads.com/uid?=abd?utm_source=partnerize&utm_medium=affiliate&utm_campaign=88849&utm_content=2-500037&clickId=12345" --metrics ./tests/results/timings/pihole --batch-size 8 --re "^banners?[_.-]" ascii;
RUST_BACKTRACE=1 /usr/bin/time -v -a -o ./tests/results/memory/pihole_nwr ./target/release/reef --baselines --doc "beacons2212.testingads.com/uid?=abd?utm_source=partnerize&utm_medium=affiliate&utm_campaign=88849&utm_content=2-500037&clickId=1" --metrics ./tests/results/timings/pihole --batch-size 8 --re "^beacons?[0-9]*[_.-]" ascii;
RUST_BACKTRACE=1 /usr/bin/time -v -a -o ./tests/results/memory/pihole_nwr ./target/release/reef --baselines --doc "counters223.testingads.com/uid?=abd?utm_source=partnerize&utm_medium=affiliate&utm_campaign=88849&utm_content=2-500037&clickId=2" --metrics ./tests/results/timings/pihole --batch-size 8 --re "^count(ers?)?[0-9]*[_.-]" ascii;
RUST_BACKTRACE=1 /usr/bin/time -v -a -o ./tests/results/memory/pihole_nwr ./target/release/reef --baselines --doc "mads.testingads.com/uid?=abd?utm_source=partnerize&utm_medium=affiliate&utm_campaign=88849&utm_content=2-500037&clickId=11233456" --metrics ./tests/results/timings/pihole --batch-size 8 --re "^mads\." ascii;
RUST_BACKTRACE=1 /usr/bin/time -v -a -o ./tests/results/memory/pihole_nwr ./target/release/reef --baselines --doc "pixel.testing.facebook.com/uid?=abd?utm_source=partnerize&utm_medium=affiliate&utm_campaign=88849&utm_content=2-500037&click1234" --metrics ./tests/results/timings/pihole --batch-size 8 --re "^pixels?[-.]" ascii;
RUST_BACKTRACE=1 /usr/bin/time -v -a -o ./tests/results/memory/pihole_nwr ./target/release/reef --baselines --doc "statistics19902.testing.facebook.com/uid?=abd?utm_source=partnerize&utm_medium=affiliate&utm_campaign=88849&utm_content=2-500037" --metrics ./tests/results/timings/pihole --batch-size 8 --re "^stat(s|istics)?[0-9]*[_.-]" ascii;